### PR TITLE
Job setup template

### PR DESCRIPTION
**Pull request by balanza**
A new template including all the tasks needed when starting a new job on a Node project. The idea is to include this template at the beginning of a job and let it deal with:
1. ~code checkout~
1. Node.js setup
1. dependencies installation

More details can be found [README](https://github.com/pagopa/azure-pipeline-templates/blob/project-setup-template/templates/node-job-setup/README.md).

### CODE REVIEW

**Comment by balanza** [comment]
I removed code checkout, it make sense to have it separated

**Comment by gquadrati** [comment]
> I removed code checkout, it make sense to have it separated

Do you plan to have a 'checkout' template or we add it manually without any abstraction?

**Comment by balanza** [comment]
> > I removed code checkout, it make sense to have it separated
> 
> Do you plan to have a 'checkout' template or we add it manually without any abstraction?

Didn't make my mind yet, to be honest. Suggestions?

**Pull request merged**
